### ISSUE TITLE
Guess what OS works best, WHO KNOWS? Linux and tar.gz OMG CAN'T COMPREHEND. Or Currupted?

### ISSUE THREAD

**Issue by bryan806** [TorrenTV/TorrenTV#65]
I can't install tar.gz just for my simple library on my capsule its really difficult to use this software, i can't understand why people even still use it. maybe windows makes people stupid? I JUST NEED THIS TO WORK. 1 day. Great application.

**Comment by bryan806** [comment]
my following mission i'll definitely check/investigate folders at least all of the following AppData/ ProgramFiles/ System32/ WINDOWS %BOOT & Antivirus scan at rescue mode and my data usage IMPORTANT MOST PEOPLE HAVE SAFE GAURD, it allows 3 OVERAGES. I'll be on chat MY ISP the details follow.

**Comment by bryan806** [comment]
Why idk well i do, i went over 350gb toll from dloading my harddrive backup but that was 250gb out of my 500GB and who knows! My data was at 700 GB estimated a and hulu device(s), I'd say this is closed some sort. I really am not satisfied with any of it!

I guess we will see what gets done by next year by the way its looking, NO UPDATES, NO ADVICE for help?

What OS works better, isnt that obvious to let someone know which is more stable? 

I never learned how to install .tar.gz on linux, TOO COMPLICATED TO ME. Can't Grasp.

**Comment by barrabinfc** [comment]
WTFuck..

I guess you're overreacting , a paranoia dream state. I've readed the source code, there's nothing that indicated that this is a backdoor. I know he is not responsive, but maybe he just doesn't have the will to maintain and fix bugs, since programming really does take your time. And also because Popcorn-time added airplay/xbmc support, so TorrenTV has no "hot-new feature" nowadays. Please read the code before you start screaming FUD, it's 400 lines of code, for christ sake.

I'm maintening a different branch, with many bugfixes and overall refactor , since the app code was hackish and hard to maintain and add new features. I think with this refactor, maintaining will be much easier.

https://github.com/barrabinfc/torrenTv/tree/vlc

The project is not dead. I will submit a pull&request and start closing the issues , but please, this is not a COMPANY FUNDED project, so don't be an asshole for a product that you don't helped shit to create.

Anyway, have you tried Popcorn-Time ? It also allows everything that TorrenTV is doing nowadays, and also better subtitles and codecs support.

https://www.popcorntime.io/

**Comment by bryan806** [comment]
there you happy? this project might not be dead, but sure as hell nobody helping. why is that? nobody want to be responsible? sorry for my mouth, JUST SIMPLE OBSERVATIONS. my data is my MONEY&LIFE who plays with that? #TROLLS and I MEAN ALOT OF PEOPLE. That's why i hate bad people so much. Sorry. I really appreciate your tone and explanation. Makes a lot of sense.

**Comment by barrabinfc** [comment]
Hey bryan! Try popcorn-time , you'll get less headaches! Still beta software, but more mature.

Lol, you're correct, nobody helping. Unfortunately, this is a common problem with open source software.
Do you see how even in 2015, there's no professional Open Source Video Editors, Image Editors and others common useful software? Such a shame... but putting these complex software together really take time, expertise, money and a lot of work and people. It's impossible to do on your own on your mama basement, and it's really hard to create a healthy and productive community around a software to keep the ball rolling without you.

Unfortunately, this project doesn't have any community around it. There's no forum,  no wiki, just a bunch of broken code and a web-page. We need to fix that, but you know, it's hard, takes times, nobody did it before, so why should we do it? I'm also lazy, i want to do others things with my life than correct bugs and improve a useful (but not unique and special) software.

Streaming torrent is a new technology, and AFAIK, only `peerflix` has implemented. The `bittorrent` guys implemented 2 years ago, but never opened the source code to the community. There's no other bittorrent client that allows streaming, even though `peerflix` is almost two years old and `Popcorn-time` hit all the major headlines worldwide.

There's a lot of work being done around this technology, but it's not USER READY with a GUI Interface. Awesome work is being done on `https://github.com/feross/webtorrent`, rocket science stuff, and it's coming FAST. So in the near future, you may not even need to download a Bittorent Client, you will be able to download/stream directly from your browser!

Anyway, thanks for your input, at least it got the ball running again.
